import Vue from 'vue'
import {
  Vuetify,
  VApp,
  VNavigationDrawer,
  VFooter,
  VList,
  VBtn,
  VIcon,
  VGrid,
  VToolbar,
  VTextField,
  VSelect,
  VResponsive,
  VRadioGroup,
  VDatePicker,
  VCard,
  VDialog,
  VPagination,
  VAvatar,
  VBtnToggle,
  VCheckbox,
  VTabs,
  VTooltip,
  VSwitch,
  VMessages,
  VAlert,
  VForm,
  VMenu,
  VDivider,
  VDataTable,
  transitions
} from 'vuetify'
import 'vuetify/src/stylus/app.styl'

Vue.use(Vuetify, {rtl: true,
  components: {
    "v-app": VApp,
    "v-navigation-drawer": VNavigationDrawer,
    "v-footer": VFooter,
    "v-list": VList,
    "v-btn": VBtn,
    "v-icon": VIcon,
    "v-grid": VGrid,
    "v-toolbar": VToolbar,
    "v-text-field": VTextField,
    "v-select": VSelect,
    "v-responsive": VResponsive,
    "v-radio-group": VRadioGroup,
    "v-vate-picker": VDatePicker,
    "v-card": VCard,
    "v-dialog": VDialog,
    "v-pagination": VPagination,
    "v-avatar": VAvatar,
    "v-btn-toggle": VBtnToggle,
    "v-checkbox": VCheckbox,
    "v-tabs": VTabs,
    "v-tooltip": VTooltip,
    "v-switch": VSwitch,
    "v-messages": VMessages,
    "v-alert": VAlert,
    "v-form": VForm,
    "v-menu": VMenu,
    "v-divider": VDivider,
    "v-data-table": VDataTable,
    transitions
  },
  theme: {
    primary: "#01579B",
    secondary: "#90A4AE",
    accent: "#F57C00",
    error: "#f44336",
    warning: "#ffeb3b",
    info: "#2196f3",
    success: "#4caf50"
  },
})
